= Camel Fuse Jenkins Demo

This is a small bundle that wil be used to demonstrate the JBoss Fuse fabric deployment with Jenkins pipelines.  This
bundle has very simple Camel Jetty route that displays a greeting.


=== Assumptions

* http://www.sonatype.org/[Nexus] is setup and has repositories configured
to deploy snapshots and releases
* https://jenkins.io/index.html[jenkins] is setup and running
* The demo requires a Version Control System(VCS), this demo uses https://gogs.io/[gogs], a tiny local git server which
is will be used as VCS in the application but you can use any VCS, but make sure to update the `<scm>` section of the `pom.xml`


== Enabling PublicKey Login in JBoss Fuse

Refer to https://github.com/kameshsampath/fuse-fabric-pipelines/blob/master/README.adoc[JBoss Fuse Fabric Pipelines], which details
the steps required to enable JAAS SSH Public key login to JBoss Fuse console.

== Deploying

All the deployments are done via Jenkins, since its in CI/CD mode any changes to the application, commit
and push to the source code repository will trigger the build

== Pipeline Stages

This demo application has the following pipeline stages

* *Checkout* - this stage checks out the code from version control, and applies the Jenkins pipeline from
  link:./Jenkinsfile[Jenkinsfile]
* *Build and Test* - this performs the maven build and unit test on the source code
* *Integration Tests* - this step does any integration test if any, this demo does not have have IT tests but this stage
acts as a placeholder
* *Staging* - this deploys the build snapshot artifact to Nexus snapshots repository configured
in the `distribution management` section of `pom.xml`
* *Fuse Dev Deploy* - this step fires a set of https://github.com/kameshsampath/fuse-fabric-pipelines/blob/master/profile_update.karaf[karaf commands]
to deploy the application in JBoss Fuse

Finally there is  Workflow approval - which is used to show promotion of artifacts to Nexus releases repository
and which can be later used by production pipelines to deploy it in production

NOTE: this demo does not cover the job that performs release to production, but it could be a similar jenkins job as this
one with bit of variation and additional steps

== License

Copyright 2017 Kamesh Sampath

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


